### ISSUE TITLE
electron updater

### ISSUE THREAD

**Issue by seiyria** [LandOfTheRair/mod-toolkit#26]
so people can get updates directly from github instead of having to download and update manually

**Comment by tangmeme-i** [comment]
Senior, please tell me about the zip package generated after packaging with electron updater on the Mac. After decompression, it shows that you don't have permission to open the application. I display the contents of the package and view the execution file in the MacOS file in the format of manuscript. As a result, I can't start this compressed package after the update process is com
<img width="255" alt="截屏2022-02-14 下午4 58 27" src="https://user-images.githubusercontent.com/68841765/153832073-b2c63d64-602e-4faf-99fc-430d8dd5801b.png">
pleted. It has been bothering me for a long time. Please solve my doubts. Thank you very much

**Comment by seiyria** [comment]
I think you might be in the wrong place @tangmeme-i.
